/* Generated By:JavaCC: Do not edit this line. analizadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface analizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INIT = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int BOOLEANO = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int PI = 11;
  /** RegularExpression Id. */
  int EULER = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int INPUT = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int ELSE_IF = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int DEFINE_FUNC = 24;
  /** RegularExpression Id. */
  int GET_RETURN_FUNC = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int FALSE = 27;
  /** RegularExpression Id. */
  int VOID = 28;
  /** RegularExpression Id. */
  int SUMA = 29;
  /** RegularExpression Id. */
  int RESTA = 30;
  /** RegularExpression Id. */
  int MULTI = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int IGUAL_QUE = 33;
  /** RegularExpression Id. */
  int DIFERENTE_QUE = 34;
  /** RegularExpression Id. */
  int MAYOR_QUE = 35;
  /** RegularExpression Id. */
  int MENOR_QUE = 36;
  /** RegularExpression Id. */
  int MAYOR_IGUAL_QUE = 37;
  /** RegularExpression Id. */
  int MENOR_IGUAL_QUE = 38;
  /** RegularExpression Id. */
  int ASIGNA = 39;
  /** RegularExpression Id. */
  int FIN_LINE = 40;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 41;
  /** RegularExpression Id. */
  int LLAVE_DER = 42;
  /** RegularExpression Id. */
  int PAREN_IZQ = 43;
  /** RegularExpression Id. */
  int PAREN_DER = 44;
  /** RegularExpression Id. */
  int CORCH_IZQ = 45;
  /** RegularExpression Id. */
  int CORCH_DER = 46;
  /** RegularExpression Id. */
  int DOBLE_PUNTO = 47;
  /** RegularExpression Id. */
  int COMA = 48;
  /** RegularExpression Id. */
  int PUNTO = 49;
  /** RegularExpression Id. */
  int NOMBRE_VAR = 50;
  /** RegularExpression Id. */
  int NUMERO = 51;
  /** RegularExpression Id. */
  int CADENA = 52;
  /** RegularExpression Id. */
  int CARACTER = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"init\"",
    "\"end\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"string\"",
    "\"pi\"",
    "\"euler\"",
    "\"constant\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"print\"",
    "\"read\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"while\"",
    "\"do\"",
    "\"define\"",
    "\"get\"",
    "\"true\"",
    "\"false\"",
    "\"void\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=?\"",
    "\"!=?\"",
    "\">?\"",
    "\"<?\"",
    "\">=?\"",
    "\"<=?\"",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "<NOMBRE_VAR>",
    "<NUMERO>",
    "<CADENA>",
    "<CARACTER>",
  };

}
